### ISSUE TITLE
Didn't work for me..

### ISSUE THREAD

**Issue by escobestflow** [tisho/framer-hints#1]
First added to my project. Didn't work. Then I checked your example and had errors and didn't work. FYI, I'm a Framer noob. =)
![img_2393](https://cloud.githubusercontent.com/assets/22537417/18981952/73fdca72-86b0-11e6-8beb-cb4fd2204204.PNG)

**Comment by tisho** [comment]
Hi @escobestflow! This functionality is now built into Framer (see http://blog.framerjs.com/posts/improved-sharing.html), so you don't need to use this plugin. I'll mark it as deprecated.

**Comment by escobestflow** [comment]
Good to know, thanks. Doesn't really say how to turn off the hinting, though. Do you happen to know how?

**Comment by tisho** [comment]
At the top of your file, put:

```
Framer.Extras.Hints.disable()
```

**Comment by escobestflow** [comment]
Just found it before you replied =) Sorry, I hate to waste people's time on obvious questions.
Thanks again!

**Comment by escobestflow** [comment]
Hi Tisho, I see that you cannot message users on github so I'm going to go out on a limb and ask you for your help here.. Do you happen to know about SVGs in Framer? All I want to be able to do is scale a heart SVG I created in Sketch without it looking blurry when it gets bigger. Ive researched this all day and can't find a good solution. Can you please help? Thanks, Luis

**Comment by tisho** [comment]
Hey, I recommend that you join the Framer Facebook group for questions like these (https://www.facebook.com/groups/framerjs). It's full of super insightful people who should be able to help you out.

Keeping scaled images (be it SVG or raster) looking sharp is a little tricky. Let's say you wanted to scale a 100x100 SVG heart to 200x200 (from scale 1 to scale 2). Since scaling down an image often makes it look a little better than scaling it up, where it gets blurrier, what you can do is make the layer 200x200, make the SVG take up the whole width/height of that layer, so the SVG heart itself starts out at 200x200. Then you scale that layer down to 0.5, which would make it appear as 100x100. When you want to animate the image, you animate from 0.5 to 1, instead of from 1 to 2.
